from __future__ import annotations

from pathlib import Path

from repoverity.config import Config
from repoverity.engine import AuditOptions, audit_repository


def test_analyzer_never_executes_target_import_time_code(tmp_path: Path) -> None:
    marker = tmp_path / "EXECUTED"
    (tmp_path / "sitecustomize.py").write_text(
        f'from pathlib import Path\nPath({str(marker)!r}).write_text("bad")\n', encoding="utf-8"
    )
    pkg = tmp_path / "evil"
    pkg.mkdir()
    (pkg / "__init__.py").write_text(
        f'from pathlib import Path\nPath({str(marker)!r}).write_text("bad")\n', encoding="utf-8"
    )
    (pkg / "module.py").write_text("import subprocess\nVALUE=1\n", encoding="utf-8")
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert result.stats.files_analyzed == 3
    assert not marker.exists()


def test_malformed_python_is_analysis_issue_not_crash(tmp_path: Path) -> None:
    (tmp_path / "broken.py").write_text("def nope(:\n", encoding="utf-8")
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert any(issue.kind == "parse-error" for issue in result.issues)


def test_binary_py_isolated(tmp_path: Path) -> None:
    (tmp_path / "binary.py").write_bytes(b"\xff\xfe\x00")
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert any(issue.kind == "decode-error" for issue in result.issues)


def test_large_file_is_bounded(tmp_path: Path) -> None:
    (tmp_path / "huge.py").write_text("#" + "x" * 1_000_100, encoding="utf-8")
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert any(issue.kind == "size-limit" for issue in result.issues)


def test_unicode_and_space_filename(tmp_path: Path) -> None:
    (tmp_path / "résumé file.py").write_text("VALUE=1\n", encoding="utf-8")
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert result.stats.files_analyzed == 1


def test_generated_file_marker_is_skipped(tmp_path: Path) -> None:
    (tmp_path / "generated.py").write_text(
        "# Generated by fixture\nimport requests\n", encoding="utf-8"
    )
    result = audit_repository(tmp_path, Config(), AuditOptions())
    assert result.stats.files_analyzed == 0
