"""Safe, deterministic source discovery and parsing."""

from __future__ import annotations

import ast
from collections.abc import Iterable
from dataclasses import dataclass
from fnmatch import fnmatch
import os
from pathlib import Path
import tokenize

from repoverity.models import AnalysisIssue


MAX_FILE_BYTES = 1_000_000
MAX_TOTAL_BYTES = 50_000_000
MAX_PYTHON_FILES = 5_000
_GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "automatically generated",
)


@dataclass(frozen=True, slots=True)
class SourceFile:
    path: Path
    relpath: str
    text: str
    tree: ast.Module | None
    is_test: bool

    @property
    def lines(self) -> tuple[str, ...]:
        return tuple(self.text.splitlines())

    @property
    def loc(self) -> int:
        return sum(1 for line in self.text.splitlines() if line.strip())


def _matches_pattern(relpath: str, pattern: str) -> bool:
    normalized = relpath.replace("\\", "/")
    clean = pattern.replace("\\", "/")
    while clean.startswith("./"):
        clean = clean[2:]
    if fnmatch(normalized, clean):
        return True
    if clean.endswith("/**"):
        prefix = clean[:-3].rstrip("/")
        return normalized == prefix or normalized.startswith(prefix + "/")
    return False


def _excluded(relpath: str, patterns: Iterable[str]) -> bool:
    return any(_matches_pattern(relpath, pattern) for pattern in patterns)


def _is_generated(text: str) -> bool:
    header = "\n".join(text.splitlines()[:8]).lower()
    return any(marker in header for marker in _GENERATED_MARKERS)


def _is_test_path(relpath: str) -> bool:
    parts = relpath.replace("\\", "/").split("/")
    filename = parts[-1]
    return "tests" in parts or filename.startswith("test_") or filename.endswith("_test.py")


def _read_source(path: Path) -> str:
    with tokenize.open(path) as handle:
        return handle.read()


def discover_sources(
    root: Path,
    exclude_patterns: tuple[str, ...],
    only_paths: frozenset[str] | None = None,
) -> tuple[tuple[SourceFile, ...], tuple[AnalysisIssue, ...], int]:
    """Discover Python files without following symlinks outside or inside the tree."""
    sources: list[SourceFile] = []
    issues: list[AnalysisIssue] = []
    skipped = 0
    total_bytes = 0

    for dirpath, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        current = Path(dirpath)
        kept_dirs: list[str] = []
        for dirname in sorted(dirnames):
            candidate = current / dirname
            try:
                rel = candidate.relative_to(root).as_posix()
            except ValueError:
                skipped += 1
                continue
            if candidate.is_symlink() or _excluded(rel + "/", exclude_patterns):
                skipped += 1
                continue
            kept_dirs.append(dirname)
        dirnames[:] = kept_dirs

        for filename in sorted(filenames):
            if not filename.endswith(".py"):
                continue
            path = current / filename
            try:
                relpath = path.relative_to(root).as_posix()
            except ValueError:
                skipped += 1
                continue
            if _excluded(relpath, exclude_patterns):
                skipped += 1
                continue
            if only_paths is not None and relpath not in only_paths:
                continue
            if path.is_symlink():
                skipped += 1
                issues.append(AnalysisIssue(relpath, "symlink-skipped", "symlinked source was not analyzed"))
                continue
            try:
                size = path.stat().st_size
            except OSError as exc:
                skipped += 1
                issues.append(AnalysisIssue(relpath, "stat-error", str(exc)))
                continue
            if size > MAX_FILE_BYTES:
                skipped += 1
                issues.append(
                    AnalysisIssue(
                        relpath,
                        "size-limit",
                        f"file is {size} bytes; per-file analysis limit is {MAX_FILE_BYTES}",
                    )
                )
                continue
            if total_bytes + size > MAX_TOTAL_BYTES or len(sources) >= MAX_PYTHON_FILES:
                skipped += 1
                issues.append(
                    AnalysisIssue(
                        relpath,
                        "repository-limit",
                        "repository analysis limits reached; remaining Python files were skipped",
                    )
                )
                continue
            try:
                text = _read_source(path)
            except (OSError, UnicodeError, SyntaxError) as exc:
                skipped += 1
                issues.append(AnalysisIssue(relpath, "decode-error", str(exc)))
                continue
            if _is_generated(text):
                skipped += 1
                continue
            try:
                tree = ast.parse(text, filename=relpath)
            except (SyntaxError, ValueError, MemoryError, RecursionError) as exc:
                tree = None
                issues.append(AnalysisIssue(relpath, "parse-error", str(exc)))
            sources.append(SourceFile(path, relpath, text, tree, _is_test_path(relpath)))
            total_bytes += size

    sources.sort(key=lambda source: source.relpath)
    return tuple(sources), tuple(issues), skipped
