"""Canonical public metadata for every RepoVerity v0.1 rule."""

from __future__ import annotations

from dataclasses import dataclass

from repoverity.models import Confidence, EvidenceLevel, Severity


@dataclass(frozen=True, slots=True)
class RuleMeta:
    rule_id: str
    category: str
    severity: Severity
    confidence: Confidence
    evidence_level: EvidenceLevel
    title: str
    summary: str
    mechanism: str
    recommendation: str
    exception_note: str
    limitations: str
    bad_example: str
    acceptable_example: str
    tags: tuple[str, ...]


_RULES: tuple[RuleMeta, ...] = (
    RuleMeta(
        "DEP101",
        "dependency-reality",
        Severity.HIGH,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "Third-party import is not declared",
        "A production import appears to come from a third-party distribution absent from project dependency metadata.",
        "Clean installs can fail at import time when a dependency is only present on the author machine.",
        "Declare the distribution in project dependencies, or document/configure why the import is provided out-of-band.",
        "Some imports are supplied by platform images, namespace packages, optional extras, vendored code, or distribution/import-name aliases.",
        "RepoVerity uses stdlib/local-module detection, installed package metadata, and a small verified alias map; unknown aliases can still create false positives.",
        "import requests  # but requests is absent from project dependencies",
        "# pyproject.toml declares requests; source imports requests",
        ("runtime-correctness", "release-risk"),
    ),
    RuleMeta(
        "DEP102",
        "dependency-reality",
        Severity.LOW,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Declared runtime dependency has no static import evidence",
        "A runtime dependency is declared but no analyzed production source imports its known top-level package.",
        "Unused dependencies increase install surface, supply-chain exposure, and maintenance burden.",
        "Confirm whether the dependency is dynamically loaded or packaging-only; remove it if it has no runtime role.",
        "Plugins, entry points, subprocess tools, dynamic imports, and framework discovery may use a dependency without a static import.",
        "Static import absence is evidence, not proof of non-use; this rule is deliberately low severity.",
        'dependencies = ["requests"]  # source never imports requests',
        "A plugin distribution loaded through entry points is documented and suppressed with rationale.",
        ("release-risk", "maintainability"),
    ),
    RuleMeta(
        "DEP103",
        "dependency-reality",
        Severity.HIGH,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "Declared Python minimum conflicts with source syntax",
        "Source parses on the analyzer runtime but fails when parsed using the project's declared minimum Python grammar.",
        "Users on a claimed-supported Python version can fail before application logic runs.",
        "Raise the declared minimum Python version or rewrite the incompatible syntax and test the minimum version in CI.",
        "The CPython AST feature-version parser is best-effort grammar compatibility, not a complete runtime compatibility proof.",
        "This rule detects syntax-level incompatibility only; library/API availability requires separate checks.",
        'requires-python = ">=3.9" while code uses Python 3.10-only match syntax',
        "requires-python matches the oldest grammar actually used and CI runs that interpreter.",
        ("runtime-correctness", "release-risk"),
    ),
    RuleMeta(
        "ABS201",
        "architecture",
        Severity.MEDIUM,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Pass-through wrapper candidate",
        "Most public methods directly delegate to one collaborator and add little observable behavior.",
        "Layers that do not validate, translate, cache, retry, enforce policy, or define a contract can add cognitive and debugging hops.",
        "Keep the boundary if it is intentional; otherwise consider exposing the collaborator or collapsing the wrapper.",
        "Adapters, facades, dependency-injection seams, API compatibility layers, and plugin contracts may intentionally be thin.",
        "RepoVerity only flags wrappers with multiple public methods and a high direct-delegation ratio; it does not auto-remove them.",
        "class Client: methods only return self._inner.same_method(...)",
        "An adapter translates errors, validates input, records metrics, or implements an external contract.",
        ("cognitive-overhead", "maintainability"),
    ),
    RuleMeta(
        "ABS202",
        "architecture",
        Severity.LOW,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Single-method class candidate",
        "A class exposes one public behavior without visible inheritance, registration, or meaningful state contract.",
        "A class can impose construction and navigation overhead when a function would express the same behavior more directly.",
        "Confirm whether framework/runtime identity is required; otherwise consider a function or a more explicit abstraction.",
        "Framework contracts, runtime dispatch, testing seams, future compatibility promises, and dependency injection can justify the class.",
        "Decorated classes and classes with explicit bases are excluded to reduce framework false positives.",
        "class Formatter: def format(self, text): ...  # no state or contract",
        "class Plugin(BasePlugin): def run(self): ...  # framework contract",
        ("cognitive-overhead", "maintainability"),
    ),
    RuleMeta(
        "ABS203",
        "architecture",
        Severity.MEDIUM,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "Nested exception shell immediately re-raises",
        "A nested try/except catches an exception only to issue a bare re-raise while an outer try already encloses it.",
        "Redundant exception shells increase nesting without changing recovery, translation, cleanup, or observability.",
        "Remove the redundant inner shell or add the boundary behavior that justifies it.",
        "A debugger breakpoint convention or instrumentation injected outside the visible source can make a shell intentional.",
        "The rule intentionally ignores translated exceptions, finally cleanup, retries, logging, and non-trivial handlers.",
        "try:\n    try: work()\n    except Exception:\n        raise\nexcept Exception: recover()",
        "except ProtocolError as exc: raise DomainError(...) from exc",
        ("cognitive-overhead", "maintainability"),
    ),
    RuleMeta(
        "NAM301",
        "naming",
        Severity.LOW,
        Confidence.LOW,
        EvidenceLevel.HEURISTIC,
        "Generic identifier in domain-heavy function",
        "A long-lived generic local name is used in a function whose surrounding symbols expose more specific domain vocabulary.",
        "Generic names increase rereading cost because meaning must be reconstructed from assignments and call sites.",
        "Rename the long-lived value to the domain concept it represents if that name remains accurate across its lifetime.",
        "Generic names are often ideal for short scopes, generic algorithms, serialization layers, or truly domain-neutral values.",
        "This is a heuristic and is never a high-severity claim; short-lived loop variables are excluded.",
        "def reconcile_invoice(...): data = ...; ... many lines using data ...",
        "for item in items: ...  # tiny conventional scope",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "NAM302",
        "naming",
        Severity.LOW,
        Confidence.MEDIUM,
        EvidenceLevel.HEURISTIC,
        "Public API name is too generic",
        "A public top-level symbol uses a generic name that does not communicate its observable operation.",
        "Public names become navigation and documentation surfaces; vague names push semantic cost onto every caller.",
        "Prefer a verb/noun phrase that states the domain operation or returned abstraction.",
        "Framework-mandated names and intentionally generic library primitives can be appropriate.",
        "The candidate name set is intentionally narrow to avoid policing naming style generally.",
        "def process_data(...): ...",
        "def parse_invoice_rows(...): ...",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "COM401",
        "comments",
        Severity.LOW,
        Confidence.LOW,
        EvidenceLevel.HEURISTIC,
        "Comment appears to restate nearby syntax",
        "A narrow comment pattern describes the immediately following operation without visible rationale or constraint language.",
        "Narration comments can become stale while adding little information beyond readable code.",
        "Remove the comment or replace it with the reason, invariant, unit, protocol constraint, or tradeoff that is not obvious from code.",
        "Teaching code, generated tutorials, accessibility needs, or unusually dense algorithms can justify descriptive comments.",
        "Only a small set of narration patterns is detected; rationale/security/spec/TODO comments are explicitly excluded.",
        "# return users\nreturn users",
        "# Keep ordering stable because the downstream signature includes list position.",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "COM402",
        "comments",
        Severity.INFO,
        Confidence.LOW,
        EvidenceLevel.HEURISTIC,
        "Narration comment cluster",
        "Several syntax-restating comments occur in a small line window.",
        "Line-by-line narration increases visual noise and often signals that code structure or naming carries too little intent.",
        "Consider removing narration and strengthening names/structure; keep comments that preserve rationale or constraints.",
        "Tutorials, examples, and deliberately pedagogical modules may be expected to narrate operations.",
        "The cluster is derived from COM401-style narrow candidates and should not gate CI by default.",
        "# get user\n...\n# check user\n...\n# return result\n...",
        "A compact rationale block explains a protocol edge case before non-obvious code.",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "DEAD501",
        "dead-surface",
        Severity.LOW,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Unused parameter candidate",
        "A function parameter has no load reference in its body and is not recognized as a compatibility/callback placeholder.",
        "Unused parameters can indicate speculative API surface, stale contracts, or incomplete implementation.",
        "Remove it when the signature is private and controlled, or document/suppress the compatibility contract that requires it.",
        "Overrides, callbacks, framework signatures, decorators, abstract APIs, and deliberately ignored underscore parameters are legitimate.",
        "Methods on classes with explicit bases and common callback signatures are excluded; dynamic framework behavior can still be missed.",
        "def transform(payload, options): return payload  # options unused",
        "def on_event(event, _context): ...  # explicit ignored compatibility parameter",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "DEAD502",
        "dead-surface",
        Severity.LOW,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Unused private helper candidate",
        "A private top-level function has no static name or attribute reference elsewhere in analyzed Python source.",
        "Dead helpers preserve obsolete concepts, enlarge review surface, and can mislead maintainers about supported paths.",
        "Remove the helper if it is truly dead, or document/suppress dynamic registration/reflection use.",
        "String-based registration, decorators implemented outside the repository, reflection, and framework discovery may consume private symbols indirectly.",
        "The rule intentionally targets private top-level functions only and is lower severity than a proven unreachable path.",
        "def _legacy_parse(...): ...  # no references",
        "@registry.register\ndef _plugin_hook(...): ...  # decorated, dynamically consumed",
        ("maintainability", "cognitive-overhead"),
    ),
    RuleMeta(
        "DEAD504",
        "dead-surface",
        Severity.MEDIUM,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "Placeholder production branch",
        "A non-test, non-abstract production path contains a pass-only branch/function or raises NotImplementedError.",
        "Reachable placeholders can silently skip required behavior or fail only after deployment reaches an untested path.",
        "Implement the path, make the abstraction explicitly abstract, or remove unreachable/speculative surface.",
        "Intentional no-op protocol branches and extension points can be legitimate when clearly documented and structurally marked.",
        "Abstract methods, Protocol/ABC-style classes, tests, and ellipsis-only typing stubs are excluded where identifiable.",
        "def save(...): raise NotImplementedError",
        "@abstractmethod\ndef save(...): raise NotImplementedError",
        ("runtime-correctness", "maintainability"),
    ),
    RuleMeta(
        "TST602",
        "test-boundaries",
        Severity.MEDIUM,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Error branch lacks direct test signal",
        "A public boundary-like function raises an explicit exception but tests do not reference both the symbol and exception/raises behavior.",
        "Failure paths often survive happy-path tests and are disproportionately important at parsing, validation, configuration, and I/O boundaries.",
        "Add a focused test that drives the error branch and asserts the observable failure contract.",
        "Tests may reach the branch indirectly through higher-level APIs without naming the underlying symbol or exception.",
        "This is a static reference map, not coverage instrumentation; absence means 'no direct evidence found,' not 'untested with certainty.'",
        "parse_config() raises ConfigError, but tests contain no parse_config + raises/ConfigError evidence",
        "test_parse_config_rejects_invalid_toml uses pytest.raises(ConfigError)",
        ("test-gap", "runtime-correctness"),
    ),
    RuleMeta(
        "TST603",
        "test-boundaries",
        Severity.MEDIUM,
        Confidence.MEDIUM,
        EvidenceLevel.INFERRED,
        "Parser/input boundary lacks malformed-input fixture signal",
        "A parse/decode/load/validate boundary has branching or exceptions but no direct test signal using malformed/invalid/error input vocabulary.",
        "AI-assisted parsers often look plausible on happy paths while malformed inputs expose assumptions, crashes, or silent acceptance.",
        "Add malformed, empty, boundary-size, or invalid-shape fixtures tied to the parser's documented contract.",
        "Property-based tests or table-driven fixtures may provide excellent malformed-input coverage without using the searched vocabulary.",
        "RepoVerity looks for direct symbol references plus a narrow invalid-input vocabulary; it does not claim measured coverage.",
        "def parse_manifest(text): ... branches ...; tests only cover valid manifest",
        "test_parse_manifest_invalid_header() drives malformed input and asserts failure",
        ("test-gap", "runtime-correctness"),
    ),
    RuleMeta(
        "TST604",
        "test-boundaries",
        Severity.MEDIUM,
        Confidence.HIGH,
        EvidenceLevel.INFERRED,
        "CLI entry point lacks integration smoke-test signal",
        "Project metadata declares a console script but tests show no subprocess/runner/--help style invocation evidence for it.",
        "Unit tests of command internals can miss packaging, entry-point wiring, argument parsing, and exit-code failures.",
        "Add at least one installed/entry-point smoke test for --help/version and one behavior/exit-code path.",
        "A separate external acceptance suite may exercise the packaged CLI outside the repository test tree.",
        "Static test-text evidence cannot see remote/private acceptance systems, so suppression with rationale is appropriate there.",
        "[project.scripts] tool=... but tests only call internal functions",
        "subprocess.run([sys.executable, '-m', 'tool', '--help'], ...) asserts exit 0",
        ("test-gap", "release-risk"),
    ),
    RuleMeta(
        "REL701",
        "release-hygiene",
        Severity.MEDIUM,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "Package metadata is incomplete or inconsistent",
        "Core packaging/release metadata expected for a distributable CLI is missing or points to absent files.",
        "Incomplete metadata creates install, licensing, compatibility, discovery, and release ambiguity that often appears only at publication time.",
        "Complete the reported metadata fields and ensure referenced README/license/entry-point files exist.",
        "Private applications not intended for distribution may intentionally omit public package metadata.",
        "The rule checks a small packaging contract, not every PyPI metadata recommendation.",
        "pyproject has no requires-python or points readme to a missing file",
        "name/version/requires-python/license/readme/CLI entry point are internally consistent",
        ("release-risk", "maintainability"),
    ),
    RuleMeta(
        "REL704",
        "release-hygiene",
        Severity.MEDIUM,
        Confidence.HIGH,
        EvidenceLevel.VERIFIED,
        "CI does not exercise declared Python range edges",
        "The project declares a bounded supported Python range, but GitHub workflow text does not include both the minimum and highest supported minor versions.",
        "A package can claim compatibility that no automated runner verifies, allowing syntax/API drift at range edges.",
        "Add CI jobs for the minimum and highest supported Python minors; keep the matrix intentionally small.",
        "Compatibility may be tested in another CI provider or reusable workflow that is not visible in the repository text.",
        "The rule currently recognizes bounded requires-python ranges and GitHub workflow text; external CI requires suppression/configuration.",
        "requires-python='>=3.11,<3.15' but workflow only runs 3.13",
        "CI includes 3.11 and 3.14 jobs for >=3.11,<3.15",
        ("release-risk", "runtime-correctness"),
    ),
)

_RULE_MAP = {rule.rule_id: rule for rule in _RULES}


def all_rules() -> tuple[RuleMeta, ...]:
    return _RULES


def get_rule(rule_id: str) -> RuleMeta | None:
    return _RULE_MAP.get(rule_id.upper())
